//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp.My_Newfolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShriNivash1234
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Rollno { get; set; }
        public string Collage { get; set; }
        public string Location { get; set; }
    }
}
